// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://tojkfqpqdgvndjeqrwov.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvamtmcXBxZGd2bmRqZXFyd292Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM0MzkxMDEsImV4cCI6MjA0OTAxNTEwMX0.xjEY2KU2bwLbVCaGE8bK-nqHCCllYqqTO12NyNxUyC0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);